spring:
    # 数据库链接配置
    datasource:
        url: jdbc:mysql://localhost:3306/cinema?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123
        # 链接池
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            # 链接池初始化大小
            initial-size: 8
            # 最大活跃数
            max-active: 16
            # 最小空闲数
            min-idle: 1
            # 最大等待时间
            max-wait: 60000

# mybatis配置
mybatis:
    check-config-location: true
    #  配置xml路径
    mapper-locations: "classpath:mybatis/mapper/*Mapper.xml"
    #  配置model包路径
    type-aliases-package: "com.example.mybatisdemo.entity.*"

#pagehelper分页插件配置
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

